spring:
  application:
    name: csv-handler
  spring:
    datasource:
      url: jdbc:mysql://localhost:3304/csv_data
      username: root
      password: vietis@123
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true



