spring:
  application:
    name: csv-handler
  datasource:
    url: jdbc:mysql://localhost:3304/csv_data
    username: root
    password: 123456a@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
